org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
org.gradle.java.home=/home/me/.jdks/jdk-21.0.6+7
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.configureondemand=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.incremental=false
kotlin.daemon.jvm.options=-Xmx2048m
