plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.kapt'
}

android {
    namespace 'com.spyboy.camxploit'
    compileSdk 35

    defaultConfig {
        applicationId "com.spyboy.camxploit"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "2.0.2"

        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }

        python {
            version "3.10"
            extractPackages "onvif", "onvif2", "zeep"
            pip {
                install "requests"
                install "idna"
                install "charset-normalizer"
                install "urllib3"
                install "certifi"
                install "beautifulsoup4"
                install "onvif-python"
                install "onvif-zeep"
                install "zeep"
                install "onvif-zeep-async"
                install "scapy"
                install "XlsxWriter"
                install "cryptography"
                install "pyOpenSSL"
                options "--no-deps", "--no-binary", "shodan"
                install "shodan"
            }
        }
    }

    buildFeatures {
        compose true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.activity:activity-compose:1.10.0'
    implementation platform('androidx.compose:compose-bom:2024.04.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation 'androidx.media3:media3-exoplayer-rtsp:1.5.1'
    implementation 'androidx.media3:media3-ui:1.5.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.5.1'
    implementation 'androidx.media3:media3-datasource:1.5.1'

    implementation 'androidx.compose.runtime:runtime-livedata'
    implementation "androidx.room:room-runtime:2.8.4"
    implementation "androidx.room:room-ktx:2.8.4"
    kapt "androidx.room:room-compiler:2.8.4"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation platform('androidx.compose:compose-bom:2024.04.01')
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
}
